package by.epam.payment_system.controller.command;

public enum CommandName {

	LOGIN, REGISTRATION, GO_TO_MAIN_PAGE, LOGOUT, SAVE_ADDITIONAL_CLIENT_DATA, EN, RU, BLOCK, UNBLOCK,
	GO_TO_TOP_UP_CARD_PAGE, TOP_UP_CARD, GO_TO_PAYMENT_PAGE, CLOSE_CARD, PAY, SHOW_ACCOUNT_LOG, SHOW_CARD_LOG,
	DEFAULT_COMMAND, CLIENT_SEARCH, ADD_CARD_TYPE, GO_TO_EDIT_PROFILE_PAGE, CHANGE_LOGIN, CHANGE_PASSWORD,
	CHANGE_CLIENT_DATA

}
