package by.epam.payment_system.controller.command;

/**
 * Describes all command names
 * 
 * @author Aleksandra Podgayskaya
 */
public enum CommandName {

	LOGIN, REGISTRATION, GO_TO_MAIN_PAGE, LOGOUT, SAVE_ADDITIONAL_CLIENT_DATA, EN, RU, BLOCK, UNBLOCK,
	GO_TO_TOP_UP_CARD_PAGE, TOP_UP_CARD, GO_TO_PAYMENT_PAGE, CLOSE_CARD, PAY, SHOW_ACCOUNT_LOG, SHOW_CARD_LOG,
	DEFAULT_COMMAND, CLIENT_SEARCH, GO_TO_EDIT_PROFILE_PAGE, CHANGE_LOGIN, CHANGE_PASSWORD, CHANGE_CLIENT_DATA,
	GO_TO_OPEN_CARD_PAGE, OPEN_MAIN_CARD, OPEN_ADDITIONAL_CARD, GO_TO_TRANSFER_PAGE, TRANSFER

}
