-- MySQL Script generated by MySQL Workbench
-- Mon Mar  1 20:06:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema payment_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema payment_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `payment_system` DEFAULT CHARACTER SET utf8 ;
USE `payment_system` ;

-- -----------------------------------------------------
-- Table `payment_system`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment_system`.`users` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `type` ENUM ('CLIENT', 'ADMIN') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `u_login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_system`.`client_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment_system`.`client_details` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `date_of_birth`  VARCHAR(45) NOT NULL,
  `personal_number_passport` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `personal_number_passport_UNIQUE` (`personal_number_passport` ASC) VISIBLE,
  INDEX `fk_client_details_users1_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_client_details_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `payment_system`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_system`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment_system`.`accounts` (
  `number_account` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `balance` DECIMAL(10,2) UNSIGNED DEFAULT 0.00, 
  `currency` ENUM ('BYN', 'USD', 'EUR') NOT NULL,
  `owner` BIGINT(20) NOT NULL,
  PRIMARY KEY (`number_account`),
  INDEX `fk_accounts_users1_idx` (`owner` ASC) VISIBLE,
  CONSTRAINT `fk_accounts_users1`
    FOREIGN KEY (`owner`)
    REFERENCES `payment_system`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_system`.`card_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment_system`.`card_types` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `image_path` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_system`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment_system`.`cards` (
  `number_card` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `account` BIGINT(20) NOT NULL,
  `type_card_id` BIGINT(20) NOT NULL,
  `status` ENUM ('MAIN', 'ADDITIONAL') NOT NULL,
  `owner` BIGINT(20) NOT NULL,
  `is_blocked` BOOLEAN DEFAULT FALSE,
  `is_closed` BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (`number_card`),
  INDEX `fk_card_types_cards1_idx` (`type_card_id` ASC) VISIBLE,
  INDEX `fk_cards_accounts1_idx` (`account` ASC) VISIBLE,
  INDEX `fk_cards_users1_idx` (`owner` ASC) VISIBLE,
  CONSTRAINT `fk_card_types_cards1`
    FOREIGN KEY (`type_card_id`)
    REFERENCES `payment_system`.`card_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cards_accounts1`
    FOREIGN KEY (`account`)
    REFERENCES `payment_system`.`accounts` (`number_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cards_users1`
    FOREIGN KEY (`owner`)
    REFERENCES `payment_system`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_system`.`transaction_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment_system`.`transaction_log` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `account` BIGINT(20) NOT NULL,
  `number_card` BIGINT(20) NOT NULL,
  `type_transaction` ENUM ('RECEIPT', 'EXPENDITURE') NOT NULL,
  `sum` DECIMAL(10,2) NOT NULL,
  `currency` ENUM ('BYN', 'USD', 'EUR') NOT NULL,
  `data_and_time` DATETIME NOT NULL,
  `bank_code` VARCHAR(45) DEFAULT 'MYSYSTEM',
  `sender_or_recipient_account` VARCHAR(45) NOT NULL,
  `ynp` VARCHAR(45) DEFAULT "SYSTEMYNP",
  `name` VARCHAR(45) DEFAULT 'PAYMENT SYSTEM',
  `purpose_of_payment` VARCHAR(200) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_transaction_log_accounts1_idx` (`account` ASC) VISIBLE,
  INDEX `fk_transaction_log_cards1_idx` (`number_card` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_log_accounts1`
    FOREIGN KEY (`account`)
    REFERENCES `payment_system`.`accounts` (`number_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_log_cards1`
    FOREIGN KEY (`number_card`)
    REFERENCES `payment_system`.`cards` (`number_card`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `payment_system`.`card_types` (`id`, `type`, `image_path`) VALUES ('1', 'Visa Classic', 'img/visa.png');
INSERT INTO `payment_system`.`card_types` (`id`, `type`, `image_path`) VALUES ('2', 'Mastercard Standart', 'img/mastercard.png');
INSERT INTO `payment_system`.`card_types` (`id`, `type`, `image_path`) VALUES ('3', 'Maestro', 'img/maestro.png');

INSERT INTO `payment_system`.`users` (`id`, `login`, `password`, `type`) VALUES ('1', 'Sane4ka', '4e1d7924d1f1b89770d7992a4efca1058e8ad51b', 'CLIENT');
INSERT INTO `payment_system`.`users` (`id`, `login`, `password`, `type`) VALUES ('2', 'Mane4ka', '4e1d7924d1f1b89770d7992a4efca1058e8ad51b', 'CLIENT');
INSERT INTO `payment_system`.`users` (`id`, `login`, `password`, `type`) VALUES ('3', 'SysAdmin', '4e1d7924d1f1b89770d7992a4efca1058e8ad51b', 'ADMIN');
INSERT INTO `payment_system`.`client_details` (`id`, `user_id`, `surname`, `name`, `patronymic`, `date_of_birth`, `personal_number_passport`, `phone`) VALUES ('1', '1', 'Подгайская', 'Александра', 'Романовна', '02.04.1992', '4020492B058PB8', '+375298136643');
INSERT INTO `payment_system`.`client_details` (`id`, `user_id`, `surname`, `name`, `patronymic`, `date_of_birth`, `personal_number_passport`, `phone`) VALUES ('2', '2', 'Подгайская', 'Мария', 'Романовна', '02.04.1992', '4020492B059PB9', '+375298136629');
INSERT INTO `payment_system`.`accounts` (`number_account`, `balance`, `currency`, `owner`) VALUES ('21081001', '50.00', 'BYN', '1');
INSERT INTO `payment_system`.`cards` (`number_card`, `account`, `type_card_id`, `status`, `owner`) VALUES ('5489333344441111', '21081001', '1', 'MAIN', '1');
INSERT INTO `payment_system`.`cards` (`number_card`, `account`, `type_card_id`, `status`, `owner`) VALUES ('5489333344441112', '21081001', '1', 'ADDITIONAL', '2');
INSERT INTO `payment_system`.`cards` (`number_card`, `account`, `type_card_id`, `status`, `owner`) VALUES ('5489333344441113', '21081001', '2', 'ADDITIONAL', '1');
INSERT INTO `payment_system`.`transaction_log` (`id`, `account`, `number_card`, `type_transaction`, `sum`, `currency`, `data_and_time`, `sender_or_recipient_account`, `purpose_of_payment`) VALUES ('1', '21081001', '5489333344441111', 'RECEIPT', '50.00', 'BYN', '21.03.14 21:48:52', '5555444433331111', 'Top up card');